const ADMIN = {
    CHANGE_BUSINESS_REGISTRATIONS: 'ADMIN_CHANGE_BUSINESS_REGISTRATIONS',
    CHANGE_BUSINESS_REGISTRATION: 'ADMIN_CHANGE_BUSINESS_REGISTRATION',
    PATCH_BUSINESS_REGISTRATION: 'ADMIN_PATCH_BUSINESS_REGISTRATION',
    CHANGE_USERS: 'ADMIN_CHANGE_USERS',
    CHANGE_USER: 'ADMIN_CHANGE_USER',
    PATCH_USER: 'ADMIN_PATCH_USER'
}

export default ADMIN;
