const AUTH = {
    CHANGE_LOGGED_IN: 'CHANGE_LOGGED_IN',
    CHANGE_USER: 'CHANGE_USER',
    CHANGE_REGISTRATION: 'CHANGE_REGISTRATION',
    CHANGE_FORGOT_PASSWORD: 'CHANGE_FORGOT_PASSWORD',
    PATCH_USER: 'PATCH_USER'
}

export default AUTH;
