const DASHBOARD = {
    CHANGE_BUSINESS_REGISTRATION: 'CHANGE_BUSINESS_REGISTRATION',
    PATCH_BUSINESS_REGISTRATION: 'PATCH_BUSINESS_REGISTRATION',
    PATCH_BANK_ACCOUNT: 'PATCH_BANK_ACCOUNT',
    CHANGE_PROFILE: 'CHANGE_PROFILE',
    PATCH_PROFILE: 'PATCH_PROFILE'
}

export default DASHBOARD;
